services:
  # Base de datos Postgre SQL
  postgres:
    image: postgres:16
    container_name: idrd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mantiene la información guardada si el contenedor se apaga
    ports:
      - "5432:5432"

  # API Backend
  backend:
    build:
      context: ../idrd-materiales-backend #Ruta del frontend
      dockerfile: Dockerfile
    container_name: idrd-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      PORT: 3000
    depends_on:
      - postgres # Se ejecuta solo después de iniciar la base de datos
    ports:
      - "3000:3000"
  
  # Frontend Angular
  frontend:
    build:
      context: ../idrd-materiales-frontend
      dockerfile: Dockerfile
    container_name: idrd-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: # Almacenamiento persistente para la BD